server:
     port: 8081
spring:
     application:
         name: mackerelpike-uims-backend-service
     datasource:
         url: jdbc:postgresql://localhost:5432/mackerelpike
         username: postgres
         password: 123456
         driver-class-nam: org.postgresql.Driver
     sleuth:
        web:
           client:
              enabled: false
        sampler:
            probability: 1.0 
     zipkin:
        base-url: http://localhost:9411/
mybatis:
      config-locations: classpath:mybatis/mybatis-config.xml
      mapper-locations: classpath:mybatis/mapper/*.xml
      type-aliases-package: com.mackerelpike.uims.backend.po

eureka:
      client:
         serviceUrl:
            defaultZone: http://localhost:8082/eureka/